### ISSUE TITLE
Bluefruit connect error

### ISSUE THREAD

**Issue by jimakos96** [AgentTroll/bt-support#1]
Hello 
I am trying to run it in my adafruit feather sense and it build successfully,it connects with the bluefruit app  but when i try to enter the UART option it says Uart Protocol can not be initialized .Have you got any idea what is causing it ?

**Comment by caojohnny** [comment]
I don’t have the hardware to check it out anymore. I can really only suggest you try comparing bluetooth transmissions between the default Arduino library for the Feather board and the Zephyr code, or just use the Arduino library as Adafruit provides support for that kind of endeavor.

Sorry I can’t help more!

**Comment by jimakos96** [comment]
Ok , just to make sure can you confirm that for your board the uart worked properly and what how did you manage to do the configuration from the arduino library to zephyr ?
